/**
 * Onvor's catalog, snapshotted from https://theonvor.com on 2026-08-04.
 *
 * Images point at the store's own Shopify CDN rather than being committed, so the
 * repo stays small and the URLs are the same ones the Storefront API will return.
 * `theonvor.com` is allowed in next.config.ts for this reason.
 *
 * This is a stand-in for live Storefront API reads. Prices and availability were
 * correct at snapshot time only - wire up `src/lib/shopify/catalog.ts` before
 * trusting either. Note every product currently carries a compare-at price
 * because the whole store is on the Azadi Sale.
 */

export type CatalogProduct = {
  handle: string;
  title: string;
  type: string;
  /** Decimal strings in PKR, as Shopify returns them. */
  price: string;
  compareAt: string | null;
  available: boolean;
  images: string[];
  options: Record<string, string[]>;
};

export const PRODUCTS: Record<string, CatalogProduct> = {
  "90-min-tee": {
    handle: "90-min-tee",
    title: "90 Min Tee",
    type: "Oversized T-shirt",
    price: "1679.30",
    compareAt: "2399.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvor90mintee1.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvor90mintee1.4.png",
    ],
    options: { Size: ["S", "M", "L", "XL"] },
  },
  "black-daily-icons-tee": {
    handle: "black-daily-icons-tee",
    title: "Black Daily Icons Tee - Women",
    type: "Oversized T-shirt",
    price: "1749.30",
    compareAt: "2499.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/DSC01139.jpg",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/DSC01143.jpg",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["Black"] },
  },
  "black-sun-to-moon-tee-men": {
    handle: "black-sun-to-moon-tee-men",
    title: "Black Sun To Moon Tee - Men",
    type: "Oversized T-shirt",
    price: "1749.30",
    compareAt: "2499.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/DSC01382.jpg",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/DSC01386.jpg",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["Black"] },
  },
  "black-sun-to-moon-tee-women": {
    handle: "black-sun-to-moon-tee-women",
    title: "Black Sun To Moon Tee - Women",
    type: "Oversized T-shirt",
    price: "1749.30",
    compareAt: "2499.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/DSC01676.jpg",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/DSC01655.jpg",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["Black"] },
  },
  "blue-sunset-escape-tee": {
    handle: "blue-sunset-escape-tee",
    title: "Blue Sunset Escape Tee - Women",
    type: "Oversized T-shirt",
    price: "1749.30",
    compareAt: "2499.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/DSC01166.jpg",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/DSC01172.jpg",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["Blue"] },
  },
  "blue-sunset-escape-tee-men": {
    handle: "blue-sunset-escape-tee-men",
    title: "Blue Sunset Escape Tee - Men",
    type: "Oversized T-shirt",
    price: "1749.30",
    compareAt: "2499.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/DSC01603.jpg",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/DSC01817.jpg",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["Blue"] },
  },
  "baggy-gray-stamp": {
    handle: "baggy-gray-stamp",
    title: "Baggy/Gray Stamp",
    type: "Baggy Trousers",
    price: "2799.30",
    compareAt: null,
    available: true,
    images: [],
    options: { Size: ["S", "M", "L", "XL"] },
  },
  "cream-daily-icons-tee": {
    handle: "cream-daily-icons-tee",
    title: "Cream Daily Icons Tee - Women",
    type: "Oversized T-shirt",
    price: "1749.30",
    compareAt: "2499.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/DSC01282.jpg",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/DSC01286.jpg",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["Cream"] },
  },
  "cream-daily-icons-tee-men": {
    handle: "cream-daily-icons-tee-men",
    title: "Cream Daily Icons Tee - Men",
    type: "Oversized T-shirt",
    price: "1749.30",
    compareAt: "2499.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/DSC01517.jpg",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/DSC01528.jpg",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["Cream"] },
  },
  "cream-wildflower-tee": {
    handle: "cream-wildflower-tee",
    title: "Cream Wildflower Tee - Men",
    type: "Oversized T-shirt",
    price: "1749.30",
    compareAt: "2499.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/DSC01480.jpg",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/DSC01483.jpg",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["Cream"] },
  },
  "grey-tee-men": {
    handle: "grey-tee-men",
    title: "Grey Tee - Men",
    type: "Oversized T-shirt",
    price: "1749.30",
    compareAt: "2499.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/DSC02069.webp",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/DSC02071.webp",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["Grey"] },
  },
  "navy-faceline-tee": {
    handle: "navy-faceline-tee",
    title: "Navy Faceline Tee - Men",
    type: "Oversized T-shirt",
    price: "1749.30",
    compareAt: "2499.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/Navy_Faceline_Tee_1.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/Navy_Faceline_Tee_6.png",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["Navy"] },
  },
  "navy-wildflower-tee": {
    handle: "navy-wildflower-tee",
    title: "Navy Wildflower Tee - Women",
    type: "Oversized T-shirt",
    price: "1749.30",
    compareAt: "2499.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/DSC01407.jpg",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/DSC01408.jpg",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["Navy"] },
  },
  "olive-green-beach-escape-tee": {
    handle: "olive-green-beach-escape-tee",
    title: "Olive Green Beach Escape Tee - Men",
    type: "Oversized T-shirt",
    price: "1749.30",
    compareAt: "2499.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/DSC01201.jpg",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/DSC01229.jpg",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["Olive Green"] },
  },
  "olive-green-beach-escape-tee-women": {
    handle: "olive-green-beach-escape-tee-women",
    title: "Olive Green Beach Escape Tee - Women",
    type: "Oversized T-shirt",
    price: "1749.30",
    compareAt: "2499.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/Muhammad_zaheeb_Image_12_e2b1ab1d-fd2f-4fef-b5e3-7a3d458da058_8273476e-bf65-43bf-b6db-2e0f7c76f472.webp",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/ChatGPT_Image_Jul_22_2026_01_03_17_PM_1.webp",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["Olive Green"] },
  },
  "olive-green-faceline-tee": {
    handle: "olive-green-faceline-tee",
    title: "Olive Green Faceline Tee - Men",
    type: "Oversized T-shirt",
    price: "1749.30",
    compareAt: "2499.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/b3c398ed-f0a4-40b9-91b9-b51aad1bd2fb.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/f5b2fe46-ff0e-4827-a59b-b9e157eed102.png",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["Olive Green"] },
  },
  "pleated-stamp-black": {
    handle: "pleated-stamp-black",
    title: "Plated/Gray Stamp",
    type: "Pleated Trouser",
    price: "2379.30",
    compareAt: "3399.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/ChatGPTImageJul23_2026_05_28_42PM_2.png?v=1786038063",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/ChatGPTImageJul23_2026_05_28_41PM_1.png?v=1786038064",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["Black"] },
  },
  "pleated-stamp-cream": {
    handle: "pleated-stamp-cream",
    title: "Plated/Black Stamp",
    type: "Pleated Trouser",
    price: "2379.30",
    compareAt: "3399.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/ChatGPTImageAug6_2026_01_46_54PM.png?v=1786039675",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/ChatGPT_Image_Aug_6_2026_02_47_36_PM.png?v=1786039746",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["Cream"] },
  },
  "refined-loose-fit-tee-black": {
    handle: "refined-loose-fit-tee-black",
    title: "Refined Loose Fit Tee - Black",
    type: "Oversized T-shirt",
    price: "1749.30",
    compareAt: "2499.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvor_printed_black_1.2.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvor_printed_black_1.png",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["Black", "Olive"] },
  },
  "refined-loose-fit-tee-black-women": {
    handle: "refined-loose-fit-tee-black-women",
    title: "Refined Loose Fit Tee - Black - Women",
    type: "Oversized T-shirt",
    price: "1749.30",
    compareAt: "2499.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/model-hero.webp",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/angle-1.webp",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["Black"] },
  },
  "refined-loose-fit-tee-olive": {
    handle: "refined-loose-fit-tee-olive",
    title: "Refined Loose Fit Tee - Olive",
    type: "Oversized T-shirt",
    price: "1749.30",
    compareAt: "2499.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorolivetee1.3.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorolivetee1.png",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["Olive", "Black"] },
  },
  "signature-baggy-beige": {
    handle: "signature-baggy-beige",
    title: "Signature Baggy - Beige",
    type: "Baggy Trousers",
    price: "2799.30",
    compareAt: "3999.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvor_baggy_beige_1.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvor_baggy_beige_1.2.png",
    ],
    options: {
      Size: ["S", "M", "L", "XL"],
      Color: ["Beige", "Charcoal", "Grey", "Black"],
    },
  },
  "signature-baggy-beige-women": {
    handle: "signature-baggy-beige-women",
    title: "Signature Baggy - Beige - Women",
    type: "Baggy Trousers",
    price: "2799.30",
    compareAt: "3999.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/Muhammad_zaheeb_Image_8_6490609c-7294-4d7d-8365-3893c303da19_44d0c500-9a21-4bb2-b25b-5a6d01f32d18.webp",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/ChatGPT_Image_Jul_16_2026_01_05_45_PM.webp",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["Beige"] },
  },
  "signature-baggy-black": {
    handle: "signature-baggy-black",
    title: "Signature Baggy - Black",
    type: "Baggy Trousers",
    price: "2799.30",
    compareAt: "3999.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/63.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/60.png",
    ],
    options: {
      Size: ["S", "M", "L", "XL"],
      Color: ["Black", "Grey", "Charcoal", "Beige"],
    },
  },
  "signature-baggy-charcoal": {
    handle: "signature-baggy-charcoal",
    title: "Signature Baggy - Charcoal",
    type: "Baggy Trousers",
    price: "2799.30",
    compareAt: "3999.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorcharcoalbeggytrouser1.5.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorcharcoalbeggytrouser1.2.png",
    ],
    options: {
      Size: ["S", "M", "L", "XL"],
      Color: ["Charcoal", "Grey", "Beige", "Black"],
    },
  },
  "signature-baggy-grey": {
    handle: "signature-baggy-grey",
    title: "Signature Baggy - Grey",
    type: "Baggy Trousers",
    price: "2799.30",
    compareAt: "3999.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorgraybeggytrouser1.4.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorgraybeggytrouser1.2.png",
    ],
    options: {
      Size: ["S", "M", "L", "XL"],
      Color: ["Grey", "Charcoal", "Beige", "Black"],
    },
  },
  "signature-shorts-black": {
    handle: "signature-shorts-black",
    title: "Signature Shorts - Black",
    type: "shorts",
    price: "1959.30",
    compareAt: "2799.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorblackshort1.4.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorblackshort1.2.png",
    ],
    options: {
      Size: ["S", "M", "L", "XL"],
      Color: ["Charcoal", "Grey", "Black"],
    },
  },
  "signature-shorts-charcoal": {
    handle: "signature-shorts-charcoal",
    title: "Signature Shorts -  Charcoal",
    type: "shorts",
    price: "1959.30",
    compareAt: "2799.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvor_charcoal_shorts_1.3.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvor_Charcoal_shorts_1.png",
    ],
    options: {
      Size: ["S", "M", "L", "XL"],
      Color: ["Charcoal", "Grey", "Black"],
    },
  },
  "signature-shorts-grey": {
    handle: "signature-shorts-grey",
    title: "Signature Shorts - Grey",
    type: "shorts",
    price: "1959.30",
    compareAt: "2799.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvor_gray_shorts_1.3.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvor_gray_shorts_1.2.png",
    ],
    options: {
      Size: ["S", "M", "L", "XL"],
      Color: ["Grey", "Black", "Charcoal"],
    },
  },
  "signature-straight-fit-beige": {
    handle: "signature-straight-fit-beige",
    title: "Signature Straight Fit - Beige",
    type: "Bottoms",
    price: "2379.30",
    compareAt: "3399.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/71.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/73.png",
    ],
    options: {
      Size: ["S", "M", "L", "XL"],
      Color: ["Beige", "Black", "Grey", "Charcoal"],
    },
  },
  "signature-straight-fit-black": {
    handle: "signature-straight-fit-black",
    title: "Signature Straight Fit - Black",
    type: "Bottoms",
    price: "2379.30",
    compareAt: "3399.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/80.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/81.png",
    ],
    options: {
      Size: ["S", "M", "L", "XL"],
      Color: ["Black", "Beige", "Grey", "Charcoal"],
    },
  },
  "signature-straight-fit-black-women": {
    handle: "signature-straight-fit-black-women",
    title: "Signature Straight Fit - Black - Women",
    type: "Bottoms",
    price: "2379.30",
    compareAt: "3399.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/Muhammad_zaheeb_Image_11_c5140936-84ce-4457-862f-8f3d83ee02c9_5163e334-904b-4642-9c2d-a0eac9f7812b.webp",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/ChatGPT_Image_Jul_16_2026_01_41_18_PM_1.webp",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["Black"] },
  },
  "signature-straight-fit-charcoal": {
    handle: "signature-straight-fit-charcoal",
    title: "Signature Straight Fit - Charcoal",
    type: "Bottoms",
    price: "2379.30",
    compareAt: "3399.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/75.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/76.png",
    ],
    options: {
      Size: ["S", "M", "L", "XL"],
      Color: ["Charcoal", "Grey", "Black", "Beige"],
    },
  },
  "signature-straight-fit-grey": {
    handle: "signature-straight-fit-grey",
    title: "Signature Straight Fit - Grey",
    type: "Bottoms",
    price: "2379.30",
    compareAt: "3399.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/77.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/79.png",
    ],
    options: {
      Size: ["S", "M", "L", "XL"],
      Color: ["Grey", "Black", "Beige", "Charcoal"],
    },
  },
  "signature-straight-fit-grey-women": {
    handle: "signature-straight-fit-grey-women",
    title: "Signature Straight Fit - Grey - Women",
    type: "Bottoms",
    price: "2379.30",
    compareAt: "3399.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/Muhammad_zaheeb_Image_2_9db63bd4-2f4e-4d4b-89a5-a5c01eb62339_f13314af-124d-495d-ab34-c8498bc5bc94.webp",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/ChatGPT_Image_Jul_16_2026_12_36_31_PM.webp",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["Grey"] },
  },
  "signature-tee-beige": {
    handle: "signature-tee-beige",
    title: "Signature Tee - Beige",
    type: "Oversized T-shirt",
    price: "1679.30",
    compareAt: "2399.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvor_beige_tee_with_icon_1.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/101.png",
    ],
    options: { Size: ["S", "M", "L", "XL"] },
  },
  "signature-tee-black": {
    handle: "signature-tee-black",
    title: "Signature Tee - Black",
    type: "Oversized T-shirt",
    price: "1679.30",
    compareAt: "2399.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvortexturedtee1.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvortexturedtee1.2.png",
    ],
    options: { Size: ["S", "M", "L", "XL"] },
  },
  "signature-tee-sky-blue": {
    handle: "signature-tee-sky-blue",
    title: "Signature Tee - Sky Blue",
    type: "Oversized T-shirt",
    price: "1679.30",
    compareAt: "2399.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorbluetee1.3.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorbluetee1.png",
    ],
    options: { Size: ["S", "M", "L", "XL"] },
  },
  "signature-tee-steel-grey": {
    handle: "signature-tee-steel-grey",
    title: "Signature Tee - Steel Grey",
    type: "Oversized T-shirt",
    price: "1679.30",
    compareAt: "2399.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/94.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/96.png",
    ],
    options: { Size: ["S", "M", "L", "XL"] },
  },
  "stamp-baggy-beige": {
    handle: "stamp-baggy-beige",
    title: "Stamp Baggy - Beige",
    type: "Baggy Trousers",
    price: "2799.30",
    compareAt: "3999.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorbeigetrouser1.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorbeigetrouser1.5.png",
    ],
    options: {
      Size: ["S", "M", "L", "XL"],
      Color: ["Beige", "Black", "Charcoal", "Grey"],
    },
  },
  "stamp-baggy-black": {
    handle: "stamp-baggy-black",
    title: "Stamp Baggy - Black",
    type: "Baggy Trousers",
    price: "2799.30",
    compareAt: "3999.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/62.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/61.png",
    ],
    options: {
      Size: ["S", "M", "L", "XL"],
      Color: ["Black", "Beige", "Charcoal", "Grey"],
    },
  },
  "stamp-baggy-camel": {
    handle: "stamp-baggy-camel",
    title: "Stamp Baggy - Camel",
    type: "Baggy Trousers",
    price: "2799.30",
    compareAt: "3999.00",
    available: true,
    images: [],
    options: { Size: ["S", "M", "L", "XL"], Color: ["Camel"] },
  },
  "stamp-baggy-charcoal": {
    handle: "stamp-baggy-charcoal",
    title: "Stamp Baggy - Charcoal",
    type: "Baggy Trousers",
    price: "2799.30",
    compareAt: "3999.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvor_baggy_charcoal_1.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvor_baggy_charcoal_1.2.png",
    ],
    options: {
      Size: ["S", "M", "L", "XL"],
      Color: ["Charcoal", "Beige", "Black", "Grey"],
    },
  },
  "stamp-baggy-grey": {
    handle: "stamp-baggy-grey",
    title: "Stamp Baggy - Grey",
    type: "Baggy Trousers",
    price: "2799.30",
    compareAt: "3999.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvor_baggy_light_gray_1.2.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvor_baggy_light_gray_1.3.png",
    ],
    options: {
      Size: ["S", "M", "L", "XL"],
      Color: ["Grey", "Beige", "Black", "Charcoal"],
    },
  },
  "stamp-rainbow-tee": {
    handle: "stamp-rainbow-tee",
    title: "Stamp Rainbow Tee",
    type: "Oversized T-shirt",
    price: "1679.30",
    compareAt: "2399.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorrainbowtee.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvor_rainbow_tee_2.png",
    ],
    options: { Size: ["S", "M", "L", "XL"] },
  },
  "stamp-shorts-black": {
    handle: "stamp-shorts-black",
    title: "Stamp Shorts - Black",
    type: "shorts",
    price: "1959.30",
    compareAt: "2799.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/83.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/84.png",
    ],
    options: {
      Size: ["S", "M", "L", "XL"],
      Color: ["Black", "Grey", "Charcoal"],
    },
  },
  "stamp-shorts-charcoal": {
    handle: "stamp-shorts-charcoal",
    title: "Stamp Shorts - Charcoal",
    type: "shorts",
    price: "1959.30",
    compareAt: "2799.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorcharcoalshorts1.2.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorcharcoalshorts1.4.png",
    ],
    options: {
      Size: ["S", "M", "L", "XL"],
      Color: ["Black", "Charcoal", "Grey"],
    },
  },
  "stamp-shorts-grey": {
    handle: "stamp-shorts-grey",
    title: "Stamp Shorts - Grey",
    type: "shorts",
    price: "1959.30",
    compareAt: "2799.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorgrayshorts1.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorgrayshorts1.4.png",
    ],
    options: {
      Size: ["S", "M", "L", "XL"],
      Color: ["Grey", "Black", "Charcoal"],
    },
  },
  "stamp-straight-fit-beige": {
    handle: "stamp-straight-fit-beige",
    title: "Stamp Straight Fit - Beige",
    type: "Bottoms",
    price: "2379.30",
    compareAt: "3399.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/65.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/66.png",
    ],
    options: {
      Size: ["S", "M", "L", "XL"],
      Color: ["Grey", "Black", "Charcoal", "Beige"],
    },
  },
  "stamp-straight-fit-black": {
    handle: "stamp-straight-fit-black",
    title: "Stamp Straight Fit - Black",
    type: "Bottoms",
    price: "2379.30",
    compareAt: "3399.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvor_loose_black_1.2.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvor_loose_black_1.3.png",
    ],
    options: {
      Size: ["S", "M", "L", "XL"],
      Color: ["Black", "Grey", "Charcoal", "Beige"],
    },
  },
  "stamp-straight-fit-charcoal": {
    handle: "stamp-straight-fit-charcoal",
    title: "Stamp Straight Fit - Charcoal",
    type: "Bottoms",
    price: "2379.30",
    compareAt: "3399.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/70.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/69.png",
    ],
    options: {
      Size: ["S", "M", "L", "XL"],
      Color: ["Grey", "Black", "Charcoal", "Beige"],
    },
  },
  "stamp-straight-fit-grey": {
    handle: "stamp-straight-fit-grey",
    title: "Stamp Straight Fit - Grey",
    type: "Bottoms",
    price: "2379.30",
    compareAt: "3399.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorlightgarytrouser1.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorlightgarytrouser1.4.png",
    ],
    options: {
      Size: ["S", "M", "L", "XL"],
      Color: ["Grey", "Black", "Charcoal", "Beige"],
    },
  },
  "stamp-tee-beige": {
    handle: "stamp-tee-beige",
    title: "Stamp Tee - Beige",
    type: "Oversized T-shirt",
    price: "1679.30",
    compareAt: "2399.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorbeigetee1.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorbeigetee1.2.png",
    ],
    options: { Size: ["S", "M", "L", "XL"] },
  },
  "stamp-tee-black": {
    handle: "stamp-tee-black",
    title: "Stamp Tee - Black",
    type: "Oversized T-shirt",
    price: "1679.30",
    compareAt: "2399.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvor_black_tee_1.3.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorblacktee1.png",
    ],
    options: { Size: ["S", "M", "L", "XL"] },
  },
  "stamp-tee-black-women": {
    handle: "stamp-tee-black-women",
    title: "Stamp Tee - Black - Women",
    type: "Oversized T-shirt",
    price: "1679.30",
    compareAt: "2399.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/Muhammad_zaheeb_Image_9_4986d65d-6b21-46d3-9b7b-1ffdd697a87a_f51a77b1-5ce4-4bdd-8c52-7b215e95d7a9.webp",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/ChatGPT_Image_Jul_20_2026_05_48_47_PM_1.webp",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["Black"] },
  },
  "stamp-tee-charcoal": {
    handle: "stamp-tee-charcoal",
    title: "Stamp Tee - Charcoal",
    type: "Oversized T-shirt",
    price: "1679.30",
    compareAt: "2399.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorcharcoaltee.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorcharcoaltee_2.png",
    ],
    options: { Size: ["S", "M", "L", "XL"] },
  },
  "stamp-tee-olive": {
    handle: "stamp-tee-olive",
    title: "Stamp Tee - Olive",
    type: "Oversized T-shirt",
    price: "1679.30",
    compareAt: "2399.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorolivegreentee1.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorolivegreentee1.2.png",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["Olive", "White"] },
  },
  "stamp-tee-steel-grey": {
    handle: "stamp-tee-steel-grey",
    title: "Stamp Tee - Steel Grey",
    type: "Oversized T-shirt",
    price: "1679.30",
    compareAt: "2399.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorgraytee1.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorgraytee1.2.png",
    ],
    options: { Size: ["S", "M", "L", "XL"] },
  },
  "stamp-tee-white": {
    handle: "stamp-tee-white",
    title: "Stamp Tee - White",
    type: "Oversized T-shirt",
    price: "1679.30",
    compareAt: "2399.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/89.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/91.png",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["White", "Olive"] },
  },
  "stamp-tee-white-women": {
    handle: "stamp-tee-white-women",
    title: "Stamp Tee - White - Women",
    type: "Oversized T-shirt",
    price: "1679.30",
    compareAt: "2399.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/ChatGPT_Image_Jul_22_2026_03_22_44_PM_1.webp",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/ChatGPT_Image_Jul_22_2026_03_22_45_PM_2.webp",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["White"] },
  },
  "urdu-calligraphy-tee-charcoal": {
    handle: "urdu-calligraphy-tee-charcoal",
    title: "Urdu Calligraphy Tee - Charcoal",
    type: "Oversized T-shirt",
    price: "1679.30",
    compareAt: "2399.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/86.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/87.png",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["Charcoal", "White"] },
  },
  "urdu-calligraphy-tee-charcoal-women": {
    handle: "urdu-calligraphy-tee-charcoal-women",
    title: "Urdu Calligraphy Tee - Charcoal - Women",
    type: "Oversized T-shirt",
    price: "1679.30",
    compareAt: "2399.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/Muhammad_zaheeb_Image_15_28e0fc08-b3e6-4fa0-bf5d-5cc69f7c5227_56fb3f4f-f483-4af4-9f30-e42d1ae1a6bc.webp",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/ChatGPT_Image_Jul_22_2026_03_47_30_PM_1.webp",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["Charcoal"] },
  },
  "urdu-calligraphy-tee-white": {
    handle: "urdu-calligraphy-tee-white",
    title: "Urdu Calligraphy Tee - White",
    type: "Oversized T-shirt",
    price: "1679.30",
    compareAt: "2399.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorWhite_Urdu_tee1.2.png",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/onvorWhite_Urdu_tee1.png",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["White", "Charcoal"] },
  },
  "white-micro-texture-tee": {
    handle: "white-micro-texture-tee",
    title: "White Micro Texture Tee - Men",
    type: "Oversized T-shirt",
    price: "1749.30",
    compareAt: "2499.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/DSC01619.jpg",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/DSC01621.jpg",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["White"] },
  },
  "white-trousers-women": {
    handle: "white-trousers-women",
    title: "White Trousers - Women",
    type: "Bottoms",
    price: "1749.30",
    compareAt: "2499.00",
    available: true,
    images: [
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/DSC01709.webp",
      "https://cdn.shopify.com/s/files/1/0996/4653/8009/files/DSC01684.jpg",
    ],
    options: { Size: ["S", "M", "L", "XL"], Color: ["Black"] },
  },
};

/** Product handles per collection, in the order the store lists them. */
export const COLLECTION_PRODUCTS: Record<string, string[]> = {
  "all-products": [
    "90-min-tee",
    "black-daily-icons-tee",
    "black-sun-to-moon-tee-women",
    "blue-sunset-escape-tee",
    "cream-daily-icons-tee",
    "cream-wildflower-tee",
    "navy-faceline-tee",
    "navy-wildflower-tee",
    "olive-green-beach-escape-tee",
    "olive-green-faceline-tee",
    "refined-loose-fit-tee-black",
    "refined-loose-fit-tee-olive",
    "signature-tee-beige",
    "signature-tee-black",
    "signature-tee-sky-blue",
    "signature-tee-steel-grey",
    "stamp-rainbow-tee",
    "stamp-tee-beige",
    "stamp-tee-black",
    "stamp-tee-charcoal",
    "stamp-tee-olive",
    "stamp-tee-steel-grey",
    "stamp-tee-white",
    "urdu-calligraphy-tee-charcoal",
    "urdu-calligraphy-tee-white",
    "white-micro-texture-tee",
    "baggy-gray-stamp",
    "pleated-stamp-black",
    "pleated-stamp-cream",
    "signature-baggy-grey",
    "signature-shorts-grey",
    "signature-straight-fit-beige",
    "stamp-baggy-black",
    "stamp-baggy-camel",
    "stamp-shorts-charcoal",
    "stamp-straight-fit-grey",
  ],
  "baggy-trouser": [
    "baggy-gray-stamp",
    "signature-baggy-grey",
    "stamp-baggy-black",
    "stamp-baggy-camel",
  ],
  bottoms: [
    "baggy-gray-stamp",
    "pleated-stamp-black",
    "pleated-stamp-cream",
    "signature-baggy-grey",
    "signature-shorts-grey",
    "signature-straight-fit-beige",
    "stamp-baggy-black",
    "stamp-baggy-camel",
    "stamp-shorts-charcoal",
    "stamp-straight-fit-grey",
  ],
  men: [
    "90-min-tee",
    "black-daily-icons-tee",
    "black-sun-to-moon-tee-women",
    "blue-sunset-escape-tee",
    "cream-daily-icons-tee",
    "cream-wildflower-tee",
    "navy-faceline-tee",
    "navy-wildflower-tee",
    "olive-green-beach-escape-tee",
    "olive-green-faceline-tee",
    "refined-loose-fit-tee-black",
    "refined-loose-fit-tee-olive",
    "signature-tee-beige",
    "signature-tee-black",
    "signature-tee-sky-blue",
    "signature-tee-steel-grey",
    "stamp-rainbow-tee",
    "stamp-tee-beige",
    "stamp-tee-black",
    "stamp-tee-charcoal",
    "stamp-tee-olive",
    "stamp-tee-steel-grey",
    "stamp-tee-white",
    "urdu-calligraphy-tee-charcoal",
    "urdu-calligraphy-tee-white",
    "white-micro-texture-tee",
    "baggy-gray-stamp",
    "pleated-stamp-black",
    "pleated-stamp-cream",
    "signature-baggy-grey",
    "signature-shorts-grey",
    "signature-straight-fit-beige",
    "stamp-baggy-black",
    "stamp-baggy-camel",
    "stamp-shorts-charcoal",
    "stamp-straight-fit-grey",
  ],
  "oversized-tees": [
    "90-min-tee",
    "black-daily-icons-tee",
    "black-sun-to-moon-tee-women",
    "blue-sunset-escape-tee",
    "cream-daily-icons-tee",
    "cream-wildflower-tee",
    "navy-faceline-tee",
    "navy-wildflower-tee",
    "olive-green-beach-escape-tee",
    "olive-green-faceline-tee",
    "refined-loose-fit-tee-black",
    "refined-loose-fit-tee-olive",
    "signature-tee-beige",
    "signature-tee-black",
    "signature-tee-sky-blue",
    "signature-tee-steel-grey",
    "stamp-rainbow-tee",
    "stamp-tee-beige",
    "stamp-tee-black",
    "stamp-tee-charcoal",
    "stamp-tee-olive",
    "stamp-tee-steel-grey",
    "stamp-tee-white",
    "urdu-calligraphy-tee-charcoal",
    "urdu-calligraphy-tee-white",
    "white-micro-texture-tee",
  ],
  "oversized-tees-men": [
    "90-min-tee",
    "black-daily-icons-tee",
    "black-sun-to-moon-tee-women",
    "blue-sunset-escape-tee",
    "cream-daily-icons-tee",
    "cream-wildflower-tee",
    "navy-faceline-tee",
    "navy-wildflower-tee",
    "olive-green-beach-escape-tee",
    "olive-green-faceline-tee",
    "refined-loose-fit-tee-black",
    "refined-loose-fit-tee-olive",
    "signature-tee-beige",
    "signature-tee-black",
    "signature-tee-sky-blue",
    "signature-tee-steel-grey",
    "stamp-rainbow-tee",
    "stamp-tee-beige",
    "stamp-tee-black",
    "stamp-tee-charcoal",
    "stamp-tee-olive",
    "stamp-tee-steel-grey",
    "stamp-tee-white",
    "urdu-calligraphy-tee-charcoal",
    "urdu-calligraphy-tee-white",
    "white-micro-texture-tee",
  ],
  "oversized-tees-women": [
    "90-min-tee",
    "black-daily-icons-tee",
    "black-sun-to-moon-tee-women",
    "blue-sunset-escape-tee",
    "cream-daily-icons-tee",
    "cream-wildflower-tee",
    "navy-faceline-tee",
    "navy-wildflower-tee",
    "olive-green-beach-escape-tee",
    "olive-green-faceline-tee",
    "refined-loose-fit-tee-black",
    "refined-loose-fit-tee-olive",
    "signature-tee-beige",
    "signature-tee-black",
    "signature-tee-sky-blue",
    "signature-tee-steel-grey",
    "stamp-rainbow-tee",
    "stamp-tee-beige",
    "stamp-tee-black",
    "stamp-tee-charcoal",
    "stamp-tee-olive",
    "stamp-tee-steel-grey",
    "stamp-tee-white",
    "urdu-calligraphy-tee-charcoal",
    "urdu-calligraphy-tee-white",
    "white-micro-texture-tee",
  ],
  "pleated-trousers": ["pleated-stamp-black", "pleated-stamp-cream"],
  shorts: ["signature-shorts-grey", "stamp-shorts-charcoal"],
  "straight-fit-trouser": ["signature-straight-fit-beige", "stamp-straight-fit-grey"],
  "t-shirt": [
    "90-min-tee",
    "black-daily-icons-tee",
    "black-sun-to-moon-tee-women",
    "blue-sunset-escape-tee",
    "cream-daily-icons-tee",
    "cream-wildflower-tee",
    "navy-faceline-tee",
    "navy-wildflower-tee",
    "olive-green-beach-escape-tee",
    "olive-green-faceline-tee",
    "refined-loose-fit-tee-black",
    "refined-loose-fit-tee-olive",
    "signature-tee-beige",
    "signature-tee-black",
    "signature-tee-sky-blue",
    "signature-tee-steel-grey",
    "stamp-rainbow-tee",
    "stamp-tee-beige",
    "stamp-tee-black",
    "stamp-tee-charcoal",
    "stamp-tee-olive",
    "stamp-tee-steel-grey",
    "stamp-tee-white",
    "urdu-calligraphy-tee-charcoal",
    "urdu-calligraphy-tee-white",
    "white-micro-texture-tee",
  ],
  "trousers-women": [
    "baggy-gray-stamp",
    "pleated-stamp-black",
    "pleated-stamp-cream",
    "signature-baggy-grey",
    "signature-shorts-grey",
    "signature-straight-fit-beige",
    "stamp-baggy-black",
    "stamp-baggy-camel",
    "stamp-shorts-charcoal",
    "stamp-straight-fit-grey",
  ],
  women: [
    "90-min-tee",
    "black-daily-icons-tee",
    "black-sun-to-moon-tee-women",
    "blue-sunset-escape-tee",
    "cream-daily-icons-tee",
    "cream-wildflower-tee",
    "navy-faceline-tee",
    "navy-wildflower-tee",
    "olive-green-beach-escape-tee",
    "olive-green-faceline-tee",
    "refined-loose-fit-tee-black",
    "refined-loose-fit-tee-olive",
    "signature-tee-beige",
    "signature-tee-black",
    "signature-tee-sky-blue",
    "signature-tee-steel-grey",
    "stamp-rainbow-tee",
    "stamp-tee-beige",
    "stamp-tee-black",
    "stamp-tee-charcoal",
    "stamp-tee-olive",
    "stamp-tee-steel-grey",
    "stamp-tee-white",
    "urdu-calligraphy-tee-charcoal",
    "urdu-calligraphy-tee-white",
    "white-micro-texture-tee",
    "baggy-gray-stamp",
    "pleated-stamp-black",
    "pleated-stamp-cream",
    "signature-baggy-grey",
    "signature-shorts-grey",
    "signature-straight-fit-beige",
    "stamp-baggy-black",
    "stamp-baggy-camel",
    "stamp-shorts-charcoal",
    "stamp-straight-fit-grey",
  ],
};

export function productsInCollection(handle: string): CatalogProduct[] {
  return (COLLECTION_PRODUCTS[handle] ?? [])
    .map((h) => PRODUCTS[h])
    .filter((p): p is CatalogProduct => Boolean(p));
}
